databaseChangeLog:
  - preConditions:
    - runningAs:
      username:  user
  - changeSet:
    id: 1
      author: Andrey
      changes:
        - createTable:
          tableName: address
            columns:
              - column:
                  name:  id
                  type:  int
                  autoIncrement:  true
                  constraints:
                    primaryKey:  true
                    nullable:  false
              -  column:
                  name:  name
                  type:  varchar(255)


CREATE TABLE "address" (
                           "address_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "customer_fk_id" int4 NOT NULL,
                           "country" varchar(255),
                           "postal_code" varchar(255),
                           "city" varchar(255),
                           "address_line" varchar(255),
                           PRIMARY KEY ("address_id")
);

CREATE TABLE "customer" (
                            "customer_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "first_name" varchar(255) NOT NULL,
                            "last_name" varchar(255) NOT NULL,
                            "balance" int4,
                            "phone" varchar(255),
                            "email" varchar(255),
                            PRIMARY KEY ("customer_id")
);

CREATE TABLE "order" (
                         "order_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         "customer_fk_id" int4 NOT NULL,
                         "product_fk_id" int4 NOT NULL,
                         "price" decimal(10,2) NOT NULL,
                         "quantity" int4 NOT NULL,
                         PRIMARY KEY ("order_id")
);

CREATE TABLE "product" (
                           "product_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           "title" varchar(255) NOT NULL,
                           "price" int4 NOT NULL,
                           "quantity" int4 NOT NULL,
                           PRIMARY KEY ("product_id")
);

ALTER TABLE "address" ADD CONSTRAINT "fk_address_customer_1" FOREIGN KEY ("customer_fk_id") REFERENCES "customer" ("customer_id");
ALTER TABLE "order" ADD CONSTRAINT "fk_order_customer_1" FOREIGN KEY ("customer_fk_id") REFERENCES "customer" ("customer_id");
ALTER TABLE "order" ADD CONSTRAINT "fk_order_product_1" FOREIGN KEY ("product_fk_id") REFERENCES "product" ("product_id");
