

spring:
  datasource:
    url: jdbc:postgresql://localhost:5635/warehousebase
    username: user
    password: password

  liquibase:
    change-log: classpath:db/changelog/changelog.sql
    drop-first: true


