spring:

#  datasource:                  # moved to docker-compose.yml
#    url: jdbc:postgresql://db/warehousebase
#    username: user
#    password: password

  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    drop-first: true          # drops database on each launch


springdoc:                    # swagger settings

#  paths-to-match: # /api/**     # limitation of endpoints visible to swagger; /api/ shall added to @RequestMapping of each Controller
#  paths-to-match:      # another variant
#    - /addresses
#    - /customers
#    - /orders
#    - /products

  swagger-ui:
    enabled: true          # set false to turn off swagger
    operations-sorter: alpha    # sets sorting order of operations
    tagsSorter: alpha           # sets sorting order of tags
    path: /sw.html        # changes path of swagger-ui to http://localhost:8088/sw.html
    filter: true          # show tags search in swagger-ui

  api-docs:
    path: /api-docs-warehouse
    enabled: true




