
server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5635/warehousebase
    username: user
    password: password

  liquibase:
    change-log: classpath:db/changelog/changelog.sql
    drop-first: true

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    path: /swagger-ui-warehouse.html
    operationsSorter: method
    tagsSorter: alpha
    version: 3.0.3
    enabled: false
  api-docs:
    path: /api-docs
    enabled: true


